### ISSUE TITLE
VisEditor 0.3.0 roadmap

### ISSUE THREAD

**Issue by kotcrab** [kotcrab/VisEditor#49]
* [x] Update to Artemis ~~1.0.1~~  ~~1.2.0~~ 1.2.1
* [x] Create `Position` component. Update:
 * [x] VisSprite
 * [x] VisText
 * [x] VisParticle
 * [x] VisSpriter
 * [x] VisSpine
* [x] Refactor EntityProxy. Add PositionOwner etc. interfaces.
* [x] Find a way to remove GroupEntityProxy
* [x] Remove "Component" from components classes names to decrease verbosity, don't forget to update tags
* [x] Deprecate content roots in favor of storing every assets in any directory. If some file is ambiguous we can store its type in metadata. (see #77)
* [x] Move away from Kryo to JSON. JSON will allow for human readable scene files and simplify keeping scenes in VCS repo. Editor JSON files should be pretty printed.
 * [x] Clean up VisTags from components
* [x] Remove editor beta update channel.
* [x] Remove code support for old editor versions, 0.3.0 won't be able to load old projects without conversion anyway.
* [x] Remove deprecated EditorPhysicsSettings, clean up EditorSceneSerializer
* [x] Reorganize `com.kotcrab.vis.editor.module.scene`
* [x] Reorganize `util` package.
* [x] Write an project converter for VisEditor 0.2.5/0.2.6.
* [x] Check TODOs

Dropped:
* ~~Merge LayerComponent and RenderableComponent~~ Reason: Entity may be on an layer but isn't renderable, for example: points, triggers etc.
* ~~Create TransformComponent, TintComponent etc. This will allow to mix SpriteComponnet with others types of Component like, MusicComponent, SoundComponent, TextComponent and others.~~
Reason: too complicated with current way of how libgdx works. Almost every type of component (sprite, particle) already stores those properites so it will be only duplicate it. Also syncing those between components would be complicated. Only `Position` component will be created.
* ~~Refactor ProtoComponents - transient components (non serializable) will be skipped for serialization but they should be recreatable from using components (like Position, Scale etc.)~~ Reason: see above, also ProtoComponents turned out to be quire good solution and won't be changed.
* ~~Refactor AssetComponent, initial idea is to create AssetReference allowing to store multiple VisAssetDescriptor, one system will them process them and create appropriate components.~~
* ~~Remove AssetComponent, each component requiring assets can store it in itself.~~ Upon further checks it would be better to leave asset component as it is.

0.3.0 will be developed in separate [branch](https://github.com/kotcrab/VisEditor/tree/editor-nxt), critical issues in 0.2.5 will be still fixed.
If you have any ideas or suggestions, please share it here or start a discussion on our [forums](http://forum.kotcrab.com/).

**Comment by kotcrab** [comment]
#### Notes for project converter
- EditorPositionComponent in Sound/Music replaced by PositionComponent

**Comment by kotcrab** [comment]
All done, finally.
